name: $pluginName
main: $pluginMain
depend: [ Kotlin, ProtocolLib ]
api-version: '1.18'
version: $version

commands:
  invcaptive:
    permission: invcaptive.command

libraries:
  - io.github.monun:tap-core:4.1.2
  - io.github.monun:kommand-core:0.3.2